package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private String guid;
	private String name;
	private String accountType;
	private String commodityGuid;
	private int commodityScu;
	private int nonStdScu;
	private String parentGuid;
	private String code;
	private String description;
	private Integer hidden;
	private Integer placeholder;

	public Accounts() {
	}

	public Accounts(String guid, String name, String accountType,
			int commodityScu, int nonStdScu) {
		this.guid = guid;
		this.name = name;
		this.accountType = accountType;
		this.commodityScu = commodityScu;
		this.nonStdScu = nonStdScu;
	}

	public Accounts(String guid, String name, String accountType,
			String commodityGuid, int commodityScu, int nonStdScu,
			String parentGuid, String code, String description, Integer hidden,
			Integer placeholder) {
		this.guid = guid;
		this.name = name;
		this.accountType = accountType;
		this.commodityGuid = commodityGuid;
		this.commodityScu = commodityScu;
		this.nonStdScu = nonStdScu;
		this.parentGuid = parentGuid;
		this.code = code;
		this.description = description;
		this.hidden = hidden;
		this.placeholder = placeholder;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getCommodityGuid() {
		return this.commodityGuid;
	}

	public void setCommodityGuid(String commodityGuid) {
		this.commodityGuid = commodityGuid;
	}

	public int getCommodityScu() {
		return this.commodityScu;
	}

	public void setCommodityScu(int commodityScu) {
		this.commodityScu = commodityScu;
	}

	public int getNonStdScu() {
		return this.nonStdScu;
	}

	public void setNonStdScu(int nonStdScu) {
		this.nonStdScu = nonStdScu;
	}

	public String getParentGuid() {
		return this.parentGuid;
	}

	public void setParentGuid(String parentGuid) {
		this.parentGuid = parentGuid;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getHidden() {
		return this.hidden;
	}

	public void setHidden(Integer hidden) {
		this.hidden = hidden;
	}

	public Integer getPlaceholder() {
		return this.placeholder;
	}

	public void setPlaceholder(Integer placeholder) {
		this.placeholder = placeholder;
	}

}
