package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Billterms generated by hbm2java
 */
public class Billterms implements java.io.Serializable {

	private String guid;
	private String name;
	private String description;
	private int refcount;
	private int invisible;
	private String parent;
	private String type;
	private Integer duedays;
	private Integer discountdays;
	private String discountNum;
	private String discountDenom;
	private Integer cutoff;

	public Billterms() {
	}

	public Billterms(String guid, String name, String description,
			int refcount, int invisible, String type) {
		this.guid = guid;
		this.name = name;
		this.description = description;
		this.refcount = refcount;
		this.invisible = invisible;
		this.type = type;
	}

	public Billterms(String guid, String name, String description,
			int refcount, int invisible, String parent, String type,
			Integer duedays, Integer discountdays, String discountNum,
			String discountDenom, Integer cutoff) {
		this.guid = guid;
		this.name = name;
		this.description = description;
		this.refcount = refcount;
		this.invisible = invisible;
		this.parent = parent;
		this.type = type;
		this.duedays = duedays;
		this.discountdays = discountdays;
		this.discountNum = discountNum;
		this.discountDenom = discountDenom;
		this.cutoff = cutoff;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getRefcount() {
		return this.refcount;
	}

	public void setRefcount(int refcount) {
		this.refcount = refcount;
	}

	public int getInvisible() {
		return this.invisible;
	}

	public void setInvisible(int invisible) {
		this.invisible = invisible;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getDuedays() {
		return this.duedays;
	}

	public void setDuedays(Integer duedays) {
		this.duedays = duedays;
	}

	public Integer getDiscountdays() {
		return this.discountdays;
	}

	public void setDiscountdays(Integer discountdays) {
		this.discountdays = discountdays;
	}

	public String getDiscountNum() {
		return this.discountNum;
	}

	public void setDiscountNum(String discountNum) {
		this.discountNum = discountNum;
	}

	public String getDiscountDenom() {
		return this.discountDenom;
	}

	public void setDiscountDenom(String discountDenom) {
		this.discountDenom = discountDenom;
	}

	public Integer getCutoff() {
		return this.cutoff;
	}

	public void setCutoff(Integer cutoff) {
		this.cutoff = cutoff;
	}

}
