package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private String guid;
	private String rootAccountGuid;
	private String rootTemplateGuid;

	public Books() {
	}

	public Books(String guid, String rootAccountGuid, String rootTemplateGuid) {
		this.guid = guid;
		this.rootAccountGuid = rootAccountGuid;
		this.rootTemplateGuid = rootTemplateGuid;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getRootAccountGuid() {
		return this.rootAccountGuid;
	}

	public void setRootAccountGuid(String rootAccountGuid) {
		this.rootAccountGuid = rootAccountGuid;
	}

	public String getRootTemplateGuid() {
		return this.rootTemplateGuid;
	}

	public void setRootTemplateGuid(String rootTemplateGuid) {
		this.rootTemplateGuid = rootTemplateGuid;
	}

}
