package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * BudgetAmounts generated by hbm2java
 */
public class BudgetAmounts implements java.io.Serializable {

	private int id;
	private String budgetGuid;
	private String accountGuid;
	private int periodNum;
	private String amountNum;
	private String amountDenom;

	public BudgetAmounts() {
	}

	public BudgetAmounts(int id, String budgetGuid, String accountGuid,
			int periodNum, String amountNum, String amountDenom) {
		this.id = id;
		this.budgetGuid = budgetGuid;
		this.accountGuid = accountGuid;
		this.periodNum = periodNum;
		this.amountNum = amountNum;
		this.amountDenom = amountDenom;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBudgetGuid() {
		return this.budgetGuid;
	}

	public void setBudgetGuid(String budgetGuid) {
		this.budgetGuid = budgetGuid;
	}

	public String getAccountGuid() {
		return this.accountGuid;
	}

	public void setAccountGuid(String accountGuid) {
		this.accountGuid = accountGuid;
	}

	public int getPeriodNum() {
		return this.periodNum;
	}

	public void setPeriodNum(int periodNum) {
		this.periodNum = periodNum;
	}

	public String getAmountNum() {
		return this.amountNum;
	}

	public void setAmountNum(String amountNum) {
		this.amountNum = amountNum;
	}

	public String getAmountDenom() {
		return this.amountDenom;
	}

	public void setAmountDenom(String amountDenom) {
		this.amountDenom = amountDenom;
	}

}
