package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Budgets generated by hbm2java
 */
public class Budgets implements java.io.Serializable {

	private String guid;
	private String name;
	private String description;
	private int numPeriods;

	public Budgets() {
	}

	public Budgets(String guid, String name, int numPeriods) {
		this.guid = guid;
		this.name = name;
		this.numPeriods = numPeriods;
	}

	public Budgets(String guid, String name, String description, int numPeriods) {
		this.guid = guid;
		this.name = name;
		this.description = description;
		this.numPeriods = numPeriods;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getNumPeriods() {
		return this.numPeriods;
	}

	public void setNumPeriods(int numPeriods) {
		this.numPeriods = numPeriods;
	}

}
