package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Commodities generated by hbm2java
 */
public class Commodities implements java.io.Serializable {

	private String guid;
	private String namespace;
	private String mnemonic;
	private String fullname;
	private String cusip;
	private int fraction;
	private int quoteFlag;
	private String quoteSource;
	private String quoteTz;

	public Commodities() {
	}

	public Commodities(String guid, String namespace, String mnemonic,
			int fraction, int quoteFlag) {
		this.guid = guid;
		this.namespace = namespace;
		this.mnemonic = mnemonic;
		this.fraction = fraction;
		this.quoteFlag = quoteFlag;
	}

	public Commodities(String guid, String namespace, String mnemonic,
			String fullname, String cusip, int fraction, int quoteFlag,
			String quoteSource, String quoteTz) {
		this.guid = guid;
		this.namespace = namespace;
		this.mnemonic = mnemonic;
		this.fullname = fullname;
		this.cusip = cusip;
		this.fraction = fraction;
		this.quoteFlag = quoteFlag;
		this.quoteSource = quoteSource;
		this.quoteTz = quoteTz;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getNamespace() {
		return this.namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public String getMnemonic() {
		return this.mnemonic;
	}

	public void setMnemonic(String mnemonic) {
		this.mnemonic = mnemonic;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getCusip() {
		return this.cusip;
	}

	public void setCusip(String cusip) {
		this.cusip = cusip;
	}

	public int getFraction() {
		return this.fraction;
	}

	public void setFraction(int fraction) {
		this.fraction = fraction;
	}

	public int getQuoteFlag() {
		return this.quoteFlag;
	}

	public void setQuoteFlag(int quoteFlag) {
		this.quoteFlag = quoteFlag;
	}

	public String getQuoteSource() {
		return this.quoteSource;
	}

	public void setQuoteSource(String quoteSource) {
		this.quoteSource = quoteSource;
	}

	public String getQuoteTz() {
		return this.quoteTz;
	}

	public void setQuoteTz(String quoteTz) {
		this.quoteTz = quoteTz;
	}

}
