package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private String guid;
	private String name;
	private String id;
	private String notes;
	private int active;
	private String discountNum;
	private String discountDenom;
	private String creditNum;
	private String creditDenom;
	private String currency;
	private int taxOverride;
	private String addrName;
	private String addrAddr1;
	private String addrAddr2;
	private String addrAddr3;
	private String addrAddr4;
	private String addrPhone;
	private String addrFax;
	private String addrEmail;
	private String shipaddrName;
	private String shipaddrAddr1;
	private String shipaddrAddr2;
	private String shipaddrAddr3;
	private String shipaddrAddr4;
	private String shipaddrPhone;
	private String shipaddrFax;
	private String shipaddrEmail;
	private String terms;
	private Integer taxIncluded;
	private String taxtable;

	public Customers() {
	}

	public Customers(String guid, String name, String id, String notes,
			int active, String discountNum, String discountDenom,
			String creditNum, String creditDenom, String currency,
			int taxOverride) {
		this.guid = guid;
		this.name = name;
		this.id = id;
		this.notes = notes;
		this.active = active;
		this.discountNum = discountNum;
		this.discountDenom = discountDenom;
		this.creditNum = creditNum;
		this.creditDenom = creditDenom;
		this.currency = currency;
		this.taxOverride = taxOverride;
	}

	public Customers(String guid, String name, String id, String notes,
			int active, String discountNum, String discountDenom,
			String creditNum, String creditDenom, String currency,
			int taxOverride, String addrName, String addrAddr1,
			String addrAddr2, String addrAddr3, String addrAddr4,
			String addrPhone, String addrFax, String addrEmail,
			String shipaddrName, String shipaddrAddr1, String shipaddrAddr2,
			String shipaddrAddr3, String shipaddrAddr4, String shipaddrPhone,
			String shipaddrFax, String shipaddrEmail, String terms,
			Integer taxIncluded, String taxtable) {
		this.guid = guid;
		this.name = name;
		this.id = id;
		this.notes = notes;
		this.active = active;
		this.discountNum = discountNum;
		this.discountDenom = discountDenom;
		this.creditNum = creditNum;
		this.creditDenom = creditDenom;
		this.currency = currency;
		this.taxOverride = taxOverride;
		this.addrName = addrName;
		this.addrAddr1 = addrAddr1;
		this.addrAddr2 = addrAddr2;
		this.addrAddr3 = addrAddr3;
		this.addrAddr4 = addrAddr4;
		this.addrPhone = addrPhone;
		this.addrFax = addrFax;
		this.addrEmail = addrEmail;
		this.shipaddrName = shipaddrName;
		this.shipaddrAddr1 = shipaddrAddr1;
		this.shipaddrAddr2 = shipaddrAddr2;
		this.shipaddrAddr3 = shipaddrAddr3;
		this.shipaddrAddr4 = shipaddrAddr4;
		this.shipaddrPhone = shipaddrPhone;
		this.shipaddrFax = shipaddrFax;
		this.shipaddrEmail = shipaddrEmail;
		this.terms = terms;
		this.taxIncluded = taxIncluded;
		this.taxtable = taxtable;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getDiscountNum() {
		return this.discountNum;
	}

	public void setDiscountNum(String discountNum) {
		this.discountNum = discountNum;
	}

	public String getDiscountDenom() {
		return this.discountDenom;
	}

	public void setDiscountDenom(String discountDenom) {
		this.discountDenom = discountDenom;
	}

	public String getCreditNum() {
		return this.creditNum;
	}

	public void setCreditNum(String creditNum) {
		this.creditNum = creditNum;
	}

	public String getCreditDenom() {
		return this.creditDenom;
	}

	public void setCreditDenom(String creditDenom) {
		this.creditDenom = creditDenom;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public int getTaxOverride() {
		return this.taxOverride;
	}

	public void setTaxOverride(int taxOverride) {
		this.taxOverride = taxOverride;
	}

	public String getAddrName() {
		return this.addrName;
	}

	public void setAddrName(String addrName) {
		this.addrName = addrName;
	}

	public String getAddrAddr1() {
		return this.addrAddr1;
	}

	public void setAddrAddr1(String addrAddr1) {
		this.addrAddr1 = addrAddr1;
	}

	public String getAddrAddr2() {
		return this.addrAddr2;
	}

	public void setAddrAddr2(String addrAddr2) {
		this.addrAddr2 = addrAddr2;
	}

	public String getAddrAddr3() {
		return this.addrAddr3;
	}

	public void setAddrAddr3(String addrAddr3) {
		this.addrAddr3 = addrAddr3;
	}

	public String getAddrAddr4() {
		return this.addrAddr4;
	}

	public void setAddrAddr4(String addrAddr4) {
		this.addrAddr4 = addrAddr4;
	}

	public String getAddrPhone() {
		return this.addrPhone;
	}

	public void setAddrPhone(String addrPhone) {
		this.addrPhone = addrPhone;
	}

	public String getAddrFax() {
		return this.addrFax;
	}

	public void setAddrFax(String addrFax) {
		this.addrFax = addrFax;
	}

	public String getAddrEmail() {
		return this.addrEmail;
	}

	public void setAddrEmail(String addrEmail) {
		this.addrEmail = addrEmail;
	}

	public String getShipaddrName() {
		return this.shipaddrName;
	}

	public void setShipaddrName(String shipaddrName) {
		this.shipaddrName = shipaddrName;
	}

	public String getShipaddrAddr1() {
		return this.shipaddrAddr1;
	}

	public void setShipaddrAddr1(String shipaddrAddr1) {
		this.shipaddrAddr1 = shipaddrAddr1;
	}

	public String getShipaddrAddr2() {
		return this.shipaddrAddr2;
	}

	public void setShipaddrAddr2(String shipaddrAddr2) {
		this.shipaddrAddr2 = shipaddrAddr2;
	}

	public String getShipaddrAddr3() {
		return this.shipaddrAddr3;
	}

	public void setShipaddrAddr3(String shipaddrAddr3) {
		this.shipaddrAddr3 = shipaddrAddr3;
	}

	public String getShipaddrAddr4() {
		return this.shipaddrAddr4;
	}

	public void setShipaddrAddr4(String shipaddrAddr4) {
		this.shipaddrAddr4 = shipaddrAddr4;
	}

	public String getShipaddrPhone() {
		return this.shipaddrPhone;
	}

	public void setShipaddrPhone(String shipaddrPhone) {
		this.shipaddrPhone = shipaddrPhone;
	}

	public String getShipaddrFax() {
		return this.shipaddrFax;
	}

	public void setShipaddrFax(String shipaddrFax) {
		this.shipaddrFax = shipaddrFax;
	}

	public String getShipaddrEmail() {
		return this.shipaddrEmail;
	}

	public void setShipaddrEmail(String shipaddrEmail) {
		this.shipaddrEmail = shipaddrEmail;
	}

	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public Integer getTaxIncluded() {
		return this.taxIncluded;
	}

	public void setTaxIncluded(Integer taxIncluded) {
		this.taxIncluded = taxIncluded;
	}

	public String getTaxtable() {
		return this.taxtable;
	}

	public void setTaxtable(String taxtable) {
		this.taxtable = taxtable;
	}

}
