package priv.nordea.db.hib;

import java.util.Set;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Entries generated by hbm2java
 */
public class Entries implements java.io.Serializable {

	private String guid;
	private String date;
	private String dateEntered;
	private String description;
	private String action;
	private String notes;
	private String quantityNum;
	private String quantityDenom;
	private String IAcct;
	private String IPriceNum;
	private String IPriceDenom;
	private String IDiscountNum;
	private String IDiscountDenom;
	private String invoice;
	private String IDiscType;
	private String IDiscHow;
	private Integer ITaxable;
	private Integer ITaxincluded;
	private String ITaxtable;
	private String BAcct;
	private String BPriceNum;
	private String BPriceDenom;
	private String bill;
	private Integer BTaxable;
	private Integer BTaxincluded;
	private String BTaxtable;
	private Integer BPaytype;
	private Integer billable;
	private Integer billtoType;
	private String billtoGuid;
	private String orderGuid;
	public Entries() {
	}

	public Entries(String guid, String date) {
		this.guid = guid;
		this.date = date;
	}

	public Entries(String guid, String date, String dateEntered,
			String description, String action, String notes,
			String quantityNum, String quantityDenom, String IAcct,
			String IPriceNum, String IPriceDenom, String IDiscountNum,
			String IDiscountDenom, String invoice, String IDiscType,
			String IDiscHow, Integer ITaxable, Integer ITaxincluded,
			String ITaxtable, String BAcct, String BPriceNum,
			String BPriceDenom, String bill, Integer BTaxable,
			Integer BTaxincluded, String BTaxtable, Integer BPaytype,
			Integer billable, Integer billtoType, String billtoGuid,
			String orderGuid) {
		this.guid = guid;
		this.date = date;
		this.dateEntered = dateEntered;
		this.description = description;
		this.action = action;
		this.notes = notes;
		this.quantityNum = quantityNum;
		this.quantityDenom = quantityDenom;
		this.IAcct = IAcct;
		this.IPriceNum = IPriceNum;
		this.IPriceDenom = IPriceDenom;
		this.IDiscountNum = IDiscountNum;
		this.IDiscountDenom = IDiscountDenom;
		this.invoice = invoice;
		this.IDiscType = IDiscType;
		this.IDiscHow = IDiscHow;
		this.ITaxable = ITaxable;
		this.ITaxincluded = ITaxincluded;
		this.ITaxtable = ITaxtable;
		this.BAcct = BAcct;
		this.BPriceNum = BPriceNum;
		this.BPriceDenom = BPriceDenom;
		this.bill = bill;
		this.BTaxable = BTaxable;
		this.BTaxincluded = BTaxincluded;
		this.BTaxtable = BTaxtable;
		this.BPaytype = BPaytype;
		this.billable = billable;
		this.billtoType = billtoType;
		this.billtoGuid = billtoGuid;
		this.orderGuid = orderGuid;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(String dateEntered) {
		this.dateEntered = dateEntered;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getQuantityNum() {
		return this.quantityNum;
	}

	public void setQuantityNum(String quantityNum) {
		this.quantityNum = quantityNum;
	}

	public String getQuantityDenom() {
		return this.quantityDenom;
	}

	public void setQuantityDenom(String quantityDenom) {
		this.quantityDenom = quantityDenom;
	}

	public String getIAcct() {
		return this.IAcct;
	}

	public void setIAcct(String IAcct) {
		this.IAcct = IAcct;
	}

	public String getIPriceNum() {
		return this.IPriceNum;
	}

	public void setIPriceNum(String IPriceNum) {
		this.IPriceNum = IPriceNum;
	}

	public String getIPriceDenom() {
		return this.IPriceDenom;
	}

	public void setIPriceDenom(String IPriceDenom) {
		this.IPriceDenom = IPriceDenom;
	}

	public String getIDiscountNum() {
		return this.IDiscountNum;
	}

	public void setIDiscountNum(String IDiscountNum) {
		this.IDiscountNum = IDiscountNum;
	}

	public String getIDiscountDenom() {
		return this.IDiscountDenom;
	}

	public void setIDiscountDenom(String IDiscountDenom) {
		this.IDiscountDenom = IDiscountDenom;
	}

	public String getInvoice() {
		return this.invoice;
	}

	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}

	public String getIDiscType() {
		return this.IDiscType;
	}

	public void setIDiscType(String IDiscType) {
		this.IDiscType = IDiscType;
	}

	public String getIDiscHow() {
		return this.IDiscHow;
	}

	public void setIDiscHow(String IDiscHow) {
		this.IDiscHow = IDiscHow;
	}

	public Integer getITaxable() {
		return this.ITaxable;
	}

	public void setITaxable(Integer ITaxable) {
		this.ITaxable = ITaxable;
	}

	public Integer getITaxincluded() {
		return this.ITaxincluded;
	}

	public void setITaxincluded(Integer ITaxincluded) {
		this.ITaxincluded = ITaxincluded;
	}

	public String getITaxtable() {
		return this.ITaxtable;
	}

	public void setITaxtable(String ITaxtable) {
		this.ITaxtable = ITaxtable;
	}

	public String getBAcct() {
		return this.BAcct;
	}

	public void setBAcct(String BAcct) {
		this.BAcct = BAcct;
	}

	public String getBPriceNum() {
		return this.BPriceNum;
	}

	public void setBPriceNum(String BPriceNum) {
		this.BPriceNum = BPriceNum;
	}

	public String getBPriceDenom() {
		return this.BPriceDenom;
	}

	public void setBPriceDenom(String BPriceDenom) {
		this.BPriceDenom = BPriceDenom;
	}

	public String getBill() {
		return this.bill;
	}

	public void setBill(String bill) {
		this.bill = bill;
	}

	public Integer getBTaxable() {
		return this.BTaxable;
	}

	public void setBTaxable(Integer BTaxable) {
		this.BTaxable = BTaxable;
	}

	public Integer getBTaxincluded() {
		return this.BTaxincluded;
	}

	public void setBTaxincluded(Integer BTaxincluded) {
		this.BTaxincluded = BTaxincluded;
	}

	public String getBTaxtable() {
		return this.BTaxtable;
	}

	public void setBTaxtable(String BTaxtable) {
		this.BTaxtable = BTaxtable;
	}

	public Integer getBPaytype() {
		return this.BPaytype;
	}

	public void setBPaytype(Integer BPaytype) {
		this.BPaytype = BPaytype;
	}

	public Integer getBillable() {
		return this.billable;
	}

	public void setBillable(Integer billable) {
		this.billable = billable;
	}

	public Integer getBilltoType() {
		return this.billtoType;
	}

	public void setBilltoType(Integer billtoType) {
		this.billtoType = billtoType;
	}

	public String getBilltoGuid() {
		return this.billtoGuid;
	}

	public void setBilltoGuid(String billtoGuid) {
		this.billtoGuid = billtoGuid;
	}

	public String getOrderGuid() {
		return this.orderGuid;
	}

	public void setOrderGuid(String orderGuid) {
		this.orderGuid = orderGuid;
	}

}
