package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Gnclock generated by hbm2java
 */
public class Gnclock implements java.io.Serializable {

	private GnclockId id;

	public Gnclock() {
	}

	public Gnclock(GnclockId id) {
		this.id = id;
	}

	public GnclockId getId() {
		return this.id;
	}

	public void setId(GnclockId id) {
		this.id = id;
	}

}
