package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * GnclockId generated by hbm2java
 */
public class GnclockId implements java.io.Serializable {

	private String hostname;
	private Integer pid;

	public GnclockId() {
	}

	public GnclockId(String hostname, Integer pid) {
		this.hostname = hostname;
		this.pid = pid;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GnclockId))
			return false;
		GnclockId castOther = (GnclockId) other;

		return ((this.getHostname() == castOther.getHostname()) || (this
				.getHostname() != null && castOther.getHostname() != null && this
				.getHostname().equals(castOther.getHostname())))
				&& ((this.getPid() == castOther.getPid()) || (this.getPid() != null
						&& castOther.getPid() != null && this.getPid().equals(
						castOther.getPid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHostname() == null ? 0 : this.getHostname().hashCode());
		result = 37 * result
				+ (getPid() == null ? 0 : this.getPid().hashCode());
		return result;
	}

}
