package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Invoices generated by hbm2java
 */
public class Invoices implements java.io.Serializable {

	private String guid;
	private String id;
	private String dateOpened;
	private String datePosted;
	private String notes;
	private int active;
	private String currency;
	private Integer ownerType;
	private String ownerGuid;
	private String terms;
	private String billingId;
	private String postTxn;
	private String postLot;
	private String postAcc;
	private Integer billtoType;
	private String billtoGuid;
	private String chargeAmtNum;
	private String chargeAmtDenom;

	public Invoices() {
	}

	public Invoices(String guid, String id, String notes, int active,
			String currency) {
		this.guid = guid;
		this.id = id;
		this.notes = notes;
		this.active = active;
		this.currency = currency;
	}

	public Invoices(String guid, String id, String dateOpened,
			String datePosted, String notes, int active, String currency,
			Integer ownerType, String ownerGuid, String terms,
			String billingId, String postTxn, String postLot, String postAcc,
			Integer billtoType, String billtoGuid, String chargeAmtNum,
			String chargeAmtDenom) {
		this.guid = guid;
		this.id = id;
		this.dateOpened = dateOpened;
		this.datePosted = datePosted;
		this.notes = notes;
		this.active = active;
		this.currency = currency;
		this.ownerType = ownerType;
		this.ownerGuid = ownerGuid;
		this.terms = terms;
		this.billingId = billingId;
		this.postTxn = postTxn;
		this.postLot = postLot;
		this.postAcc = postAcc;
		this.billtoType = billtoType;
		this.billtoGuid = billtoGuid;
		this.chargeAmtNum = chargeAmtNum;
		this.chargeAmtDenom = chargeAmtDenom;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDateOpened() {
		return this.dateOpened;
	}

	public void setDateOpened(String dateOpened) {
		this.dateOpened = dateOpened;
	}

	public String getDatePosted() {
		return this.datePosted;
	}

	public void setDatePosted(String datePosted) {
		this.datePosted = datePosted;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Integer getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(Integer ownerType) {
		this.ownerType = ownerType;
	}

	public String getOwnerGuid() {
		return this.ownerGuid;
	}

	public void setOwnerGuid(String ownerGuid) {
		this.ownerGuid = ownerGuid;
	}

	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public String getBillingId() {
		return this.billingId;
	}

	public void setBillingId(String billingId) {
		this.billingId = billingId;
	}

	public String getPostTxn() {
		return this.postTxn;
	}

	public void setPostTxn(String postTxn) {
		this.postTxn = postTxn;
	}

	public String getPostLot() {
		return this.postLot;
	}

	public void setPostLot(String postLot) {
		this.postLot = postLot;
	}

	public String getPostAcc() {
		return this.postAcc;
	}

	public void setPostAcc(String postAcc) {
		this.postAcc = postAcc;
	}

	public Integer getBilltoType() {
		return this.billtoType;
	}

	public void setBilltoType(Integer billtoType) {
		this.billtoType = billtoType;
	}

	public String getBilltoGuid() {
		return this.billtoGuid;
	}

	public void setBilltoGuid(String billtoGuid) {
		this.billtoGuid = billtoGuid;
	}

	public String getChargeAmtNum() {
		return this.chargeAmtNum;
	}

	public void setChargeAmtNum(String chargeAmtNum) {
		this.chargeAmtNum = chargeAmtNum;
	}

	public String getChargeAmtDenom() {
		return this.chargeAmtDenom;
	}

	public void setChargeAmtDenom(String chargeAmtDenom) {
		this.chargeAmtDenom = chargeAmtDenom;
	}

}
