package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Lots generated by hbm2java
 */
public class Lots implements java.io.Serializable {

	private String guid;
	private String accountGuid;
	private int isClosed;

	public Lots() {
	}

	public Lots(String guid, int isClosed) {
		this.guid = guid;
		this.isClosed = isClosed;
	}

	public Lots(String guid, String accountGuid, int isClosed) {
		this.guid = guid;
		this.accountGuid = accountGuid;
		this.isClosed = isClosed;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getAccountGuid() {
		return this.accountGuid;
	}

	public void setAccountGuid(String accountGuid) {
		this.accountGuid = accountGuid;
	}

	public int getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(int isClosed) {
		this.isClosed = isClosed;
	}

}
