package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String guid;
	private String id;
	private String notes;
	private String reference;
	private int active;
	private String dateOpened;
	private String dateClosed;
	private int ownerType;
	private String ownerGuid;

	public Orders() {
	}

	public Orders(String guid, String id, String notes, String reference,
			int active, String dateOpened, String dateClosed, int ownerType,
			String ownerGuid) {
		this.guid = guid;
		this.id = id;
		this.notes = notes;
		this.reference = reference;
		this.active = active;
		this.dateOpened = dateOpened;
		this.dateClosed = dateClosed;
		this.ownerType = ownerType;
		this.ownerGuid = ownerGuid;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getDateOpened() {
		return this.dateOpened;
	}

	public void setDateOpened(String dateOpened) {
		this.dateOpened = dateOpened;
	}

	public String getDateClosed() {
		return this.dateClosed;
	}

	public void setDateClosed(String dateClosed) {
		this.dateClosed = dateClosed;
	}

	public int getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(int ownerType) {
		this.ownerType = ownerType;
	}

	public String getOwnerGuid() {
		return this.ownerGuid;
	}

	public void setOwnerGuid(String ownerGuid) {
		this.ownerGuid = ownerGuid;
	}

}
