package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Prices generated by hbm2java
 */
public class Prices implements java.io.Serializable {

	private String guid;
	private String commodityGuid;
	private String currencyGuid;
	private String date;
	private String source;
	private String type;
	private String valueNum;
	private String valueDenom;

	public Prices() {
	}

	public Prices(String guid, String commodityGuid, String currencyGuid,
			String date, String valueNum, String valueDenom) {
		this.guid = guid;
		this.commodityGuid = commodityGuid;
		this.currencyGuid = currencyGuid;
		this.date = date;
		this.valueNum = valueNum;
		this.valueDenom = valueDenom;
	}

	public Prices(String guid, String commodityGuid, String currencyGuid,
			String date, String source, String type, String valueNum,
			String valueDenom) {
		this.guid = guid;
		this.commodityGuid = commodityGuid;
		this.currencyGuid = currencyGuid;
		this.date = date;
		this.source = source;
		this.type = type;
		this.valueNum = valueNum;
		this.valueDenom = valueDenom;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getCommodityGuid() {
		return this.commodityGuid;
	}

	public void setCommodityGuid(String commodityGuid) {
		this.commodityGuid = commodityGuid;
	}

	public String getCurrencyGuid() {
		return this.currencyGuid;
	}

	public void setCurrencyGuid(String currencyGuid) {
		this.currencyGuid = currencyGuid;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValueNum() {
		return this.valueNum;
	}

	public void setValueNum(String valueNum) {
		this.valueNum = valueNum;
	}

	public String getValueDenom() {
		return this.valueDenom;
	}

	public void setValueDenom(String valueDenom) {
		this.valueDenom = valueDenom;
	}

}
