package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Recurrences generated by hbm2java
 */
public class Recurrences implements java.io.Serializable {

	private int id;
	private String objGuid;
	private int recurrenceMult;
	private String recurrencePeriodType;
	private String recurrencePeriodStart;

	public Recurrences() {
	}

	public Recurrences(int id, String objGuid, int recurrenceMult,
			String recurrencePeriodType, String recurrencePeriodStart) {
		this.id = id;
		this.objGuid = objGuid;
		this.recurrenceMult = recurrenceMult;
		this.recurrencePeriodType = recurrencePeriodType;
		this.recurrencePeriodStart = recurrencePeriodStart;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getObjGuid() {
		return this.objGuid;
	}

	public void setObjGuid(String objGuid) {
		this.objGuid = objGuid;
	}

	public int getRecurrenceMult() {
		return this.recurrenceMult;
	}

	public void setRecurrenceMult(int recurrenceMult) {
		this.recurrenceMult = recurrenceMult;
	}

	public String getRecurrencePeriodType() {
		return this.recurrencePeriodType;
	}

	public void setRecurrencePeriodType(String recurrencePeriodType) {
		this.recurrencePeriodType = recurrencePeriodType;
	}

	public String getRecurrencePeriodStart() {
		return this.recurrencePeriodStart;
	}

	public void setRecurrencePeriodStart(String recurrencePeriodStart) {
		this.recurrencePeriodStart = recurrencePeriodStart;
	}

}
