package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Slots generated by hbm2java
 */
public class Slots implements java.io.Serializable {

	private int id;
	private String objGuid;
	private String name;
	private int slotType;
	private String int64Val;
	private String stringVal;
	private String doubleVal;
	private String timespecVal;
	private String guidVal;
	private String numericValNum;
	private String numericValDenom;
	private String gdateVal;

	public Slots() {
	}

	public Slots(int id, String objGuid, String name, int slotType) {
		this.id = id;
		this.objGuid = objGuid;
		this.name = name;
		this.slotType = slotType;
	}

	public Slots(int id, String objGuid, String name, int slotType,
			String int64Val, String stringVal, String doubleVal,
			String timespecVal, String guidVal, String numericValNum,
			String numericValDenom, String gdateVal) {
		this.id = id;
		this.objGuid = objGuid;
		this.name = name;
		this.slotType = slotType;
		this.int64Val = int64Val;
		this.stringVal = stringVal;
		this.doubleVal = doubleVal;
		this.timespecVal = timespecVal;
		this.guidVal = guidVal;
		this.numericValNum = numericValNum;
		this.numericValDenom = numericValDenom;
		this.gdateVal = gdateVal;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getObjGuid() {
		return this.objGuid;
	}

	public void setObjGuid(String objGuid) {
		this.objGuid = objGuid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getSlotType() {
		return this.slotType;
	}

	public void setSlotType(int slotType) {
		this.slotType = slotType;
	}

	public String getInt64Val() {
		return this.int64Val;
	}

	public void setInt64Val(String int64Val) {
		this.int64Val = int64Val;
	}

	public String getStringVal() {
		return this.stringVal;
	}

	public void setStringVal(String stringVal) {
		this.stringVal = stringVal;
	}

	public String getDoubleVal() {
		return this.doubleVal;
	}

	public void setDoubleVal(String doubleVal) {
		this.doubleVal = doubleVal;
	}

	public String getTimespecVal() {
		return this.timespecVal;
	}

	public void setTimespecVal(String timespecVal) {
		this.timespecVal = timespecVal;
	}

	public String getGuidVal() {
		return this.guidVal;
	}

	public void setGuidVal(String guidVal) {
		this.guidVal = guidVal;
	}

	public String getNumericValNum() {
		return this.numericValNum;
	}

	public void setNumericValNum(String numericValNum) {
		this.numericValNum = numericValNum;
	}

	public String getNumericValDenom() {
		return this.numericValDenom;
	}

	public void setNumericValDenom(String numericValDenom) {
		this.numericValDenom = numericValDenom;
	}

	public String getGdateVal() {
		return this.gdateVal;
	}

	public void setGdateVal(String gdateVal) {
		this.gdateVal = gdateVal;
	}

}
