package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Splits generated by hbm2java
 */
public class Splits implements java.io.Serializable {

	private String guid;
	private String txGuid;
	private String accountGuid;
	private String memo;
	private String action;
	private String reconcileState;
	private String reconcileDate;
	private String valueNum;
	private String valueDenom;
	private String quantityNum;
	private String quantityDenom;
	private String lotGuid;
	private Accounts account;

	public Splits() {
	}

	public Splits(String guid, String txGuid, String accountGuid, String memo,
			String action, String reconcileState, String valueNum,
			String valueDenom, String quantityNum, String quantityDenom) {
		this.guid = guid;
		this.txGuid = txGuid;
		this.accountGuid = accountGuid;
		this.memo = memo;
		this.action = action;
		this.reconcileState = reconcileState;
		this.valueNum = valueNum;
		this.valueDenom = valueDenom;
		this.quantityNum = quantityNum;
		this.quantityDenom = quantityDenom;
	}

	public Splits(String guid, String txGuid, String accountGuid, String memo,
			String action, String reconcileState, String reconcileDate,
			String valueNum, String valueDenom, String quantityNum,
			String quantityDenom, String lotGuid) {
		this.guid = guid;
		this.txGuid = txGuid;
		this.accountGuid = accountGuid;
		this.memo = memo;
		this.action = action;
		this.reconcileState = reconcileState;
		this.reconcileDate = reconcileDate;
		this.valueNum = valueNum;
		this.valueDenom = valueDenom;
		this.quantityNum = quantityNum;
		this.quantityDenom = quantityDenom;
		this.lotGuid = lotGuid;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getTxGuid() {
		return this.txGuid;
	}

	public void setTxGuid(String txGuid) {
		this.txGuid = txGuid;
	}

	public String getAccountGuid() {
		return this.accountGuid;
	}

	public void setAccountGuid(String accountGuid) {
		this.accountGuid = accountGuid;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getReconcileState() {
		return this.reconcileState;
	}

	public void setReconcileState(String reconcileState) {
		this.reconcileState = reconcileState;
	}

	public String getReconcileDate() {
		return this.reconcileDate;
	}

	public void setReconcileDate(String reconcileDate) {
		this.reconcileDate = reconcileDate;
	}

	public String getValueNum() {
		return this.valueNum;
	}

	public void setValueNum(String valueNum) {
		this.valueNum = valueNum;
	}

	public String getValueDenom() {
		return this.valueDenom;
	}

	public void setValueDenom(String valueDenom) {
		this.valueDenom = valueDenom;
	}

	public String getQuantityNum() {
		return this.quantityNum;
	}

	public void setQuantityNum(String quantityNum) {
		this.quantityNum = quantityNum;
	}

	public String getQuantityDenom() {
		return this.quantityDenom;
	}

	public void setQuantityDenom(String quantityDenom) {
		this.quantityDenom = quantityDenom;
	}

	public String getLotGuid() {
		return this.lotGuid;
	}

	public void setLotGuid(String lotGuid) {
		this.lotGuid = lotGuid;
	}

	public Accounts getAccount() {
		return account;
	}

	public void setAccount(Accounts account) {
		this.account = account;
	}

}
