package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * SqliteSequence generated by hbm2java
 */
public class SqliteSequence implements java.io.Serializable {

	private SqliteSequenceId id;

	public SqliteSequence() {
	}

	public SqliteSequence(SqliteSequenceId id) {
		this.id = id;
	}

	public SqliteSequenceId getId() {
		return this.id;
	}

	public void setId(SqliteSequenceId id) {
		this.id = id;
	}

}
