package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * TaxtableEntries generated by hbm2java
 */
public class TaxtableEntries implements java.io.Serializable {

	private int id;
	private String taxtable;
	private String account;
	private String amountNum;
	private String amountDenom;
	private int type;

	public TaxtableEntries() {
	}

	public TaxtableEntries(int id, String taxtable, String account,
			String amountNum, String amountDenom, int type) {
		this.id = id;
		this.taxtable = taxtable;
		this.account = account;
		this.amountNum = amountNum;
		this.amountDenom = amountDenom;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTaxtable() {
		return this.taxtable;
	}

	public void setTaxtable(String taxtable) {
		this.taxtable = taxtable;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAmountNum() {
		return this.amountNum;
	}

	public void setAmountNum(String amountNum) {
		this.amountNum = amountNum;
	}

	public String getAmountDenom() {
		return this.amountDenom;
	}

	public void setAmountDenom(String amountDenom) {
		this.amountDenom = amountDenom;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
