package priv.nordea.db.hib;

import java.util.Set;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private String guid;
	private String currencyGuid;
	private String num;
	private String postDate;
	private String enterDate;
	private String description;
	private Set<Splits> splits;


	public Transactions() {
	}

	public Transactions(String guid, String currencyGuid, String num) {
		this.guid = guid;
		this.currencyGuid = currencyGuid;
		this.num = num;
	}

	public Transactions(String guid, String currencyGuid, String num,
			String postDate, String enterDate, String description) {
		this.guid = guid;
		this.currencyGuid = currencyGuid;
		this.num = num;
		this.postDate = postDate;
		this.enterDate = enterDate;
		this.description = description;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getCurrencyGuid() {
		return this.currencyGuid;
	}

	public void setCurrencyGuid(String currencyGuid) {
		this.currencyGuid = currencyGuid;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getPostDate() {
		return this.postDate;
	}

	public void setPostDate(String postDate) {
		this.postDate = postDate;
	}

	public String getEnterDate() {
		return this.enterDate;
	}

	public void setEnterDate(String enterDate) {
		this.enterDate = enterDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Splits> getSplits() {
		return splits;
	}

	public void setSplits(Set<Splits> splits) {
		this.splits = splits;
	}
}
