package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Vendors generated by hbm2java
 */
public class Vendors implements java.io.Serializable {

	private String guid;
	private String name;
	private String id;
	private String notes;
	private String currency;
	private int active;
	private int taxOverride;
	private String addrName;
	private String addrAddr1;
	private String addrAddr2;
	private String addrAddr3;
	private String addrAddr4;
	private String addrPhone;
	private String addrFax;
	private String addrEmail;
	private String terms;
	private String taxInc;
	private String taxTable;

	public Vendors() {
	}

	public Vendors(String guid, String name, String id, String notes,
			String currency, int active, int taxOverride) {
		this.guid = guid;
		this.name = name;
		this.id = id;
		this.notes = notes;
		this.currency = currency;
		this.active = active;
		this.taxOverride = taxOverride;
	}

	public Vendors(String guid, String name, String id, String notes,
			String currency, int active, int taxOverride, String addrName,
			String addrAddr1, String addrAddr2, String addrAddr3,
			String addrAddr4, String addrPhone, String addrFax,
			String addrEmail, String terms, String taxInc, String taxTable) {
		this.guid = guid;
		this.name = name;
		this.id = id;
		this.notes = notes;
		this.currency = currency;
		this.active = active;
		this.taxOverride = taxOverride;
		this.addrName = addrName;
		this.addrAddr1 = addrAddr1;
		this.addrAddr2 = addrAddr2;
		this.addrAddr3 = addrAddr3;
		this.addrAddr4 = addrAddr4;
		this.addrPhone = addrPhone;
		this.addrFax = addrFax;
		this.addrEmail = addrEmail;
		this.terms = terms;
		this.taxInc = taxInc;
		this.taxTable = taxTable;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public int getTaxOverride() {
		return this.taxOverride;
	}

	public void setTaxOverride(int taxOverride) {
		this.taxOverride = taxOverride;
	}

	public String getAddrName() {
		return this.addrName;
	}

	public void setAddrName(String addrName) {
		this.addrName = addrName;
	}

	public String getAddrAddr1() {
		return this.addrAddr1;
	}

	public void setAddrAddr1(String addrAddr1) {
		this.addrAddr1 = addrAddr1;
	}

	public String getAddrAddr2() {
		return this.addrAddr2;
	}

	public void setAddrAddr2(String addrAddr2) {
		this.addrAddr2 = addrAddr2;
	}

	public String getAddrAddr3() {
		return this.addrAddr3;
	}

	public void setAddrAddr3(String addrAddr3) {
		this.addrAddr3 = addrAddr3;
	}

	public String getAddrAddr4() {
		return this.addrAddr4;
	}

	public void setAddrAddr4(String addrAddr4) {
		this.addrAddr4 = addrAddr4;
	}

	public String getAddrPhone() {
		return this.addrPhone;
	}

	public void setAddrPhone(String addrPhone) {
		this.addrPhone = addrPhone;
	}

	public String getAddrFax() {
		return this.addrFax;
	}

	public void setAddrFax(String addrFax) {
		this.addrFax = addrFax;
	}

	public String getAddrEmail() {
		return this.addrEmail;
	}

	public void setAddrEmail(String addrEmail) {
		this.addrEmail = addrEmail;
	}

	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public String getTaxInc() {
		return this.taxInc;
	}

	public void setTaxInc(String taxInc) {
		this.taxInc = taxInc;
	}

	public String getTaxTable() {
		return this.taxTable;
	}

	public void setTaxTable(String taxTable) {
		this.taxTable = taxTable;
	}

}
