package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Versions generated by hbm2java
 */
public class Versions implements java.io.Serializable {

	private String tableName;
	private int tableVersion;

	public Versions() {
	}

	public Versions(String tableName, int tableVersion) {
		this.tableName = tableName;
		this.tableVersion = tableVersion;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public int getTableVersion() {
		return this.tableVersion;
	}

	public void setTableVersion(int tableVersion) {
		this.tableVersion = tableVersion;
	}

}
