package priv.nordea.db.hib;

// Generated Jun 1, 2013 9:24:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Versions generated by hbm2java
 */
public class XAccountShop implements java.io.Serializable {

	private String accountName;
	private String shopName;

	public XAccountShop() {
	}

	public XAccountShop(String tableName, String tableVersion) {
		this.accountName = tableName;
		this.shopName = tableVersion;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String tableName) {
		this.accountName = tableName;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String tableVersion) {
		this.shopName = tableVersion;
	}

}
